services:
  api:
    build:
      context: ../api
    command: uvicorn main:app --reload --host 0.0.0.0
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ORG_ID=${OPENAI_ORG_ID}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - HOST=localhost
      - PORT=8000
    volumes:
      - ../api/app/:/usr/src/app/
  chat-manager:
    build:
      context: ../manager
    command: python app/main.py
    ports:
      - "50051:50051"
      - "50080:50080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ORG_ID=${OPENAI_ORG_ID}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - HOST=localhost
      - PORT=50051
    restart: always