"""(Hyperfocus): fix name column

Revision ID: 3e1c5ea767ba
Revises: 6615252b898f
Create Date: 2025-02-10 05:43:41.704374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1c5ea767ba'
down_revision: Union[str, None] = '6615252b898f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
