"""(UserHyperfocus): fix table relationship mappings

Revision ID: 6b8fccce6c6a
Revises: 7fec5774b7ec
Create Date: 2025-02-10 09:13:38.100807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8fccce6c6a'
down_revision: Union[str, None] = '7fec5774b7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
