"""(UserHyperfocus): adjust cascading behavior

Revision ID: 7fec5774b7ec
Revises: bdea1f4b4fb1
Create Date: 2025-02-10 09:01:14.738011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fec5774b7ec'
down_revision: Union[str, None] = 'bdea1f4b4fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
