"""(UserHyperfocus): adjust id columns

Revision ID: bdea1f4b4fb1
Revises: f14c526a7536
Create Date: 2025-02-10 08:39:16.168103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdea1f4b4fb1'
down_revision: Union[str, None] = 'f14c526a7536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('UserHyperfocus_hyperfocus_id_fkey', 'UserHyperfocus', type_='foreignkey')
    op.drop_constraint('UserHyperfocus_user_id_fkey', 'UserHyperfocus', type_='foreignkey')
    op.create_foreign_key(None, 'UserHyperfocus', 'Hyperfocus', ['hyperfocus_id'], ['name'])
    op.create_foreign_key(None, 'UserHyperfocus', 'User', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UserHyperfocus', type_='foreignkey')
    op.drop_constraint(None, 'UserHyperfocus', type_='foreignkey')
    op.create_foreign_key('UserHyperfocus_user_id_fkey', 'UserHyperfocus', 'User', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key('UserHyperfocus_hyperfocus_id_fkey', 'UserHyperfocus', 'Hyperfocus', ['hyperfocus_id'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###
