# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/message.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 28, 1, "", "protos/message.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14protos/message.proto"U\n\rRequestAIChat\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t"\x1d\n\nAIResponse\x12\x0f\n\x07message\x18\x01 \x01(\t24\n\x0b\x43hatManager\x12%\n\x06\x43hatAI\x12\x0e.RequestAIChat\x1a\x0b.AIResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "protos.message_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_REQUESTAICHAT"]._serialized_start = 24
    _globals["_REQUESTAICHAT"]._serialized_end = 109
    _globals["_AIRESPONSE"]._serialized_start = 111
    _globals["_AIRESPONSE"]._serialized_end = 140
    _globals["_CHATMANAGER"]._serialized_start = 142
    _globals["_CHATMANAGER"]._serialized_end = 194
# @@protoc_insertion_point(module_scope)
